environment.yml, readthedocs.yml, setup.py
=> Fixing readthedocs builds.

.travis.yml, setup.py
- add multiple jobs
- add a separate yt-dev test
- add a docs test
- add a deploy job
- simplify install dependencies
=> Travis update

doc/source/Fields.rst, ytree/arbor/arbor.py
=> Add vector field docs (closes Issue #12)

ytree/arbor/arbor.py, ytree/arbor/frontends/ahf/io.py
=> Fix some spelling errors. (closes Issue #6)

README.md, doc/source/Arbor.rst, doc/source/index.rst
This is for the ytree [JOSS review](https://github.com/openjournals/joss-reviews/issues/1881).
@aureliocarnero, please comment on whether you think this sufficiently addresses your comment about the github landing page. I will wait until you approve before merging. You can see the page rendered [here](https://github.com/brittonsmith/ytree/tree/readme).
=> Add statement of need and brief code demo to README.

paper/paper.md
Minor updates from the [JOSS review](https://github.com/openjournals/joss-reviews/issues/1881#issuecomment-564864133) following Issue #36.
@mgckind, please approve the PR or leave a comment if this looks good to you.
=> Paper updates from JOSS review.

.circleci/config.yml, .codecov.yml, setup.py, tests/test_lhalotree.py, ytree/visualization/tree_plot.py
This adds automated testing using circleci and fixes a small plotting bug.
=> Add circleci testing

.circleci/config.yml
Removes some tests and updates python 3.8 version.
=> Remove intermediate python versions from tests.

.circleci/config.yml
=> Add names to commands.

ytree/frontends/consistent_trees/arbor.py, ytree/utilities/io.py
This fixes the data files list for ctrees datasets that have some (but not all) empty files. I also added a progress bar for reading the locations.dat files.
=> [bugfix] account for empty ctrees files in data files list

.circleci/config.yml, setup.py
yt-4.0 has dropped python 3.5 support.
=> Drop support for python 3.5 and update circleci python version.

.circleci/config.yml, ytree/data_structures/save_arbor.py
This process never takes more than a few seconds.
=> Remove pbar.

doc/source/Examples.rst, tests/test_examples.py
This adds tests for the examples in the documentation and updates one per the recent refactor.
=> Add tests for examples and update one.

CONTRIBUTING.rst, doc/source/Arbor.rst, doc/source/Developing.rst, doc/source/api_reference.rst, ytree/frontends/consistent_trees_hdf5/arbor.py
This updates the documentation for creating new frontends following some recent refactoring.
=> Update frontend development docs

tests/test_saving.py, ytree/data_structures/save_arbor.py
This fixes a corner case bug where the entire arbor might not be saved.
=> [bugfix] fix issue with saving full arbor

doc/source/Fields.rst, doc/source/api_reference.rst, tests/test_analysis.py, ytree/data_structures/arbor.py, ytree/data_structures/fields.py, ytree/data_structures/io.py
This adds an `add_vector_field` function so that one can create vector fields for newly created analysis fields and the like.
I have also moved all the code for the `add_*_field` functions into the `FieldInfoContainer` class, which makes more sense.
=> [new feature] add add_vector_field function and move add_*_field code to FieldInfoContainer

ytree/data_structures/arbor.py
…rom forest.
This prevents an issue if data files are loaded from the current directory and a separate issue preventing 'forest' selection is `select_halos`.
=> [bugfix] directory and select_halos bugs

.circleci/config.yml
This should get testing to work again.
=> Change branch names from master to main in ci.

.circleci/config.yml, README.md, doc/source/changelog.rst
A couple more master->main changes, too.
=> update testing to python 3.9

.circleci/config.yml, ytree/data_structures/arbor.py, ytree/frontends/consistent_trees/arbor.py, ytree/utilities/io.py, ytree/utilities/testing.py
After yt switched from the vendored version of tqdm to an external dependency, the progress bars no longer support passing the increment to `update` instead of the count. This fixes the progress bars to comply to that.
=> Update progress bars for change in yt progress bar.

ytree/data_structures/arbor.py, ytree/frontends/consistent_trees/arbor.py, ytree/frontends/lhalotree/arbor.py, ytree/frontends/ytree/arbor.py
Replacing deprecated numpy types, like `np.object`.
=> Replace deprecated numpy types

doc/source/Arbor.rst, doc/source/Developing.rst, doc/source/Fields.rst, readthedocs.yml
Trying to get the api docs to build on readthedocs.
=> Try installing with pip on rtd.

.circleci/config.yml
Latest version of click currently incompatible with girder client.
=> Use click version before 8.0.

doc/source/Arbor.rst, doc/source/api_reference.rst, ytree/data_structures/arbor.py, ytree/data_structures/tree_node.py, ytree/utilities/testing.py
This adds a get_root_nodes function to return all root nodes in a forest.
=> Add get_root_nodes function

README.md
=> Add yt badge.

.circleci/config.yml, setup.py
Explicitly require yt-4.0 and use next gen circleci images.
=> setup updates

ytree/data_structures/save_arbor.py
This resolves Issue #99 without having to introduce backward incompatibility. We use the file layout of the loaded arbor to choose the file layout when saving.
=> Use file sizes of loaded arbor when only saving analysis fields.

.circleci/config.yml
This should enable saving test results for viewing on circleci.
=> Enable saving test results.

doc/source/Fields.rst, doc/source/Parallelism.rst, doc/source/index.rst
This adds a section of documentation on using ytree in parallel with examples of parallelizing over trees, halos in a single tree, multilevel parallelism, and saving intermediate results. No new code here, just examples showing novel usage.
=> Add parallel analysis docs

ytree/data_structures/save_arbor.py, ytree/utilities/io.py, ytree/utilities/testing.py, ytree/yt_frontend/data_structures.py, ytree/yt_frontend/io.py
This re-implements a couple yt utility functions locally to having to import them.
=> consume some yt utilities functions

.circleci/config.yml, pytest.ini, tests/frontends/test_ahf.py, tests/frontends/test_rockstar.py
This is an attempt to enable parallel testing on circle as a means of cutting down on job runtime.
=> enable parallelism on circleci

ytree/data_structures/io.py, ytree/frontends/consistent_trees/io.py, ytree/frontends/consistent_trees_hdf5/io.py, ytree/frontends/lhalotree/io.py, ytree/frontends/lhalotree_hdf5/io.py, ytree/frontends/moria/io.py, ytree/frontends/treefrog/io.py, ytree/frontends/ytree/io.py
This is a minor refactor of applying units to loaded data to cut down on some duplicate code. This is in service of Issue #89, but probably not all I want to do there.
=> Implement _apply_units method.

.github/workflows/python-publish.yml, MANIFEST.in
This adds a github action for uploading releases to pypi.
=> Create pypi upload action.

tests/test_analysis.py, ytree/data_structures/fields.py, ytree/data_structures/tree_node.py
If one makes a vector field out of analysis fields, the vector field version doesn't get updated after the component analysis fields are updated. This fixes that.
=> Make sure to refresh vector analysis fields after setting values.

.circleci/config.yml, setup.py, ytree/data_structures/arbor.py
This adds official support for Python 3.10 and starts using it for testing on circleci.
=> Officially support and start testing Python 3.10

README.md, doc/source/Installation.rst
ytree is now installable via conda. This adds instructions for doing that.
=> Update installation instructions to include conda option.

doc/source/conf.py
This fixes the build failures.
=> Set doc language to fix warning.

tests/frontends/test_lhalotree.py, ytree/frontends/lhalotree/utils.py
These seem to have popped up after a new version of flake8.
=> Fix flake8 errors.

.circleci/config.yml, .readthedocs.yaml, readthedocs.yml, setup.py
With yt dropping its support for Python 3.7, we will do the same here so as to keep being able to use dev yt with dev ytree.
=> Drop python 3.7 support and update circle images.

doc/source/Installation.rst
Fix code snippet line that wasn't showing up.
=> Fix doc syntax.

ytree/yt_frontend/data_structures.py
This updates the yt frontend following [PR #4426](https://github.com/yt-project/yt/pull/4426) of yt.
=> Remove validate_index_order call as that is now handled elsewhere.

.circleci/config.yml, setup.py, ytree/frontends/treefrog/io.py, ytree/yt_frontend/io.py
This updates python versions on circleci and fixes some deprecation warnings.
=> Updating python versions and fixing deprecations.

ytree/data_structures/tree_node.py
Switching out deprecated function.
=> Change deprecated numpy.in1d to isin.

ytree/data_structures/arbor.py, ytree/utilities/testing.py
This replaces a few more deprecated numpy functions.
=> Replace deprecated functions.

README.md, doc/source/Help.rst, doc/source/index.rst
Made the description slightly more general and added note about availability in help docs.
=> Generalize package description in docs

ytree/data_structures/save_arbor.py
The change was isolated from PR #183 since I don't know what will happen with that one. This fixes a minor bug in estimating the progress during an update save.
=> Get correct file numbers when doing an update save.

doc/source/Changelog.rst, doc/source/conf.py, ytree/__init__.py
This updates the version numbers and changelog for the 3.3.1 release.
=> Updates for 3.3.1 release.
