ytree-project/ytree

- doc/source/Developing.rst
- doc/source/reference.rst
- tests/test_ytree_1x.py
- ytree/arbor/arbor.py
- ytree/arbor/fields.py
- ytree/arbor/frontends/ahf/io.py
- ytree/arbor/frontends/arborarbor/arbor.py
- ytree/arbor/frontends/arborarbor/io.py
- ytree/arbor/frontends/lhalotree/io.py
- ytree/arbor/frontends/rockstar/arbor.py
- ytree/arbor/frontends/rockstar/io.py
- ytree/arbor/frontends/tree_farm/io.py
- ytree/arbor/frontends/ytree/io.py
- ytree/arbor/io.py
- ytree/arbor/tree_node.py
- ytree/utilities/testing.py
This is a refactor of the FieldIO system that removes 1 of the 3 active `FieldContainer` objects and renames the other two to allow for additional simplification. As an added bonus, we no longer store the dependencies of a given field when it is queried, thus reducing memory.
This also add vector fields, which was my original point for doing this.
> FieldIO refactor

- COPYING.txt
- tests/test_misc.py
- tests/test_select_halos.py
- ytree/arbor/arbor.py
- ytree/tree_farm/tree_farm.py
- ytree/utilities/exceptions.py
- ytree/utilities/io.py
- ytree/utilities/logger.py
This changes the blanket suppression of yt logging to one that suppresses during `yt.load` and then returns to the originally value so that logging is not suppressed in scripts. I also updated a couple copyrights and remove LHaloTree from the list of frontends that would benefit from saving and reloading because it's pretty dang fast already.
> Only suppress yt logging for yt.load

- ytree/arbor/tree_node.py
For consistency with non-root tree nodes. This will get rid of an annoying gotcha in scripts.
> Add a descendent attribute for root nodes.

- tests/test_misc.py
- ytree/arbor/io.py
This fixes an issue with rockstar data. The following script would produce an error:
```
import ytree
a = ytree.load("rockstar_halos/out_0.list")
t = a[a['mass'].argmax()]
t['prog', 'redshift']
t.save_tree()
```
The call to `t['prog', 'redshift']` would clobber the `uid` and `desc_uid` fields because the list of fields to save would be created before the tree would be setup.
> Move creation of old_fields list until after tree might be setup.

- tests/test_misc.py
- ytree/arbor/io.py
- ytree/arbor/tree_node.py
This fixes an issue where field access fails on non-root nodes of trees that have not been setup.
This will fail:
```
import ytree
a = ytree.load("rockstar/rockstar_halos/out_0.list")
t = a[a['mass'].argmax()]
f = t.ancestors[0]['desc_uid']
```
> [bugfix] fix field access on catalog arbors when tree not setup

- paper/paper.bib
This PR adds a missing DOI to the `paper.bib` file, as suggested here: https://github.com/openjournals/joss-reviews/issues/1853#issuecomment-549803761
> Add missing DOI

- paper/paper.bib
- paper/paper.md
This PR changes some of the bibtex reference names so the [JOSS paper](https://github.com/openjournals/joss-reviews/issues/1853) builds correctly. One additional reference had an incorrect name.
> Fix reference formatting issues.

- LICENSE
Following the [JOSS review](https://github.com/openjournals/joss-reviews/issues/1881), this adds the license to the appropriate location.
> Copy license from COPYING.txt to LICENSE.

- ytree/data_structures/arbor.py
- ytree/data_structures/tree_node.py
- ytree/frontends/consistent_trees/arbor.py
- ytree/frontends/lhalotree/arbor.py
- ytree/frontends/lhalotree/utils.py
- ytree/frontends/rockstar/arbor.py
This removes the remaining imports from `yt.extern.six`, which were removed from yt-4.0. This fixes Issue #44.
> Remove imports from yt.extern.six.

- ytree/frontends/rockstar/arbor.py
This fixes the situation where files names `out_000.list` and `out_000_subhalo.list` exist in the same directory. Now, either of these can be loaded.
> [bugfix] Use regular expression to detect output fields better.

- ytree/frontends/treefarm/arbor.py
Fixes an issue with how ytdata attributes are saved in yt-4.0.
> [bugfix] Check if attr is bytes or string.

- CONTRIBUTING.rst
- doc/source/Arbor.rst
- doc/source/Developing.rst
- doc/source/Examples.rst
- doc/source/Fields.rst
- doc/source/api_reference.rst
- tests/test_analysis.py
- tests/test_examples.py
- ytree/data_structures/arbor.py
- ytree/data_structures/io.py
- ytree/data_structures/save_arbor.py
- ytree/data_structures/tree_node.py
- ytree/frontends/consistent_trees_hdf5/arbor.py
- ytree/frontends/ytree/arbor.py
- ytree/frontends/ytree/io.py
- ytree/utilities/exceptions.py
This allows all analysis fields to be saved in sidecar data files and for the on-disk fields not to be rewritten if all we want to do is save new analysis fields. If you are already working from a re-saved dataset (from `Arbor.save_arbor`) and you call `save_arbor` after creating new analysis fields, only the new fields will be written if the following conditions are met:
- the default field list (`fields=None`) is provided
- the default filename is given (`filename=None`)
- the number of trees to be saved is the same as the total number in the dataset
> save analysis fields to sidecar files

- ytree/data_structures/fields.py
- ytree/frontends/treefarm/arbor.py
This makes the filename checking for treefarm datasets a bit more robust and allows it to work with merger trees made from yt hop/fof.
> [bugfix] Use regex for more robust filename check.

- .circleci/config.yml
- doc/source/Loading.rst
- setup.py
- ytree/data_structures/arbor.py
- ytree/data_structures/fields.py
- ytree/data_structures/save_arbor.py
- ytree/frontends/ahf/arbor.py
- ytree/frontends/ahf/io.py
- ytree/frontends/ytree/arbor.py
This PR relaxes the requirements that cosmology parameters, like hubble_constant, omega_matter, omega_lambda, and box_size be present within the data. It also adds more load keyword for the AHF frontend allowing the user to specify the path to the log file and to give values for all the above parameters if no log file exists.
> Relax requirements on cosmological parameters and add load options for AHF

- doc/source/Arbor.rst
- ytree/data_structures/arbor.py
This deprecates the `fields` keyword, which was not speeding things up and removes some other optimizations that were actually just taking more time.
> Trim select_halos function

- ytree/frontends/consistent_trees/arbor.py
- ytree/frontends/consistent_trees_hdf5/arbor.py
- ytree/utilities/testing.py
The `_node_io_loop` was only sorting trees by file index but the order within a single file was ending up scrambled. Trees were being iterated on out of order, creating cache misses just about every time. This will put them back in to order and seems to speed up the io loops quite a bit.
I also took the opportunity to capture the size of each tree when we have it during the plant trees phase so we can use it later in the saving. This speeds up a portion of that astronomically.
> improved sorting for node_io_loop in ctrees_group and ctrees_hdf5

- ytree/frontends/treefrog/arbor.py
- ytree/frontends/treefrog/io.py
> Treefrog frontend fixes

- tests/frontends/test_treefrog.py
- ytree/frontends/treefrog/arbor.py
This resolves Issue #98 by introducing a function to get the forest stats filename from a given data filename.
> TreeFrog: detect correct filename if data file given instead

- ytree/data_structures/arbor.py
- ytree/data_structures/io.py
- ytree/data_structures/save_arbor.py
- ytree/data_structures/tree_node.py
- ytree/frontends/treefrog/io.py
- ytree/utilities/testing.py
This renames the `_field_data` attribute associated with root `TreeNode` and `Arbor` to `field_data`, effectively making it a public-facing attribute. I have done this as accessing this attribute is the most straightforward way to combine results after running in parallel. Making it public facing will make this method seem a bit more reliable.
> Make field_data an public facing attribute.

- doc/source/Fields.rst
This corrects an error showing a loop over halos that does not use a persistent data structure, which would not allow analysis fields to be saved correctly. I've fixed this and added an expanded discussion.
> correct error in analysis field docs

- ytree/frontends/ahf/arbor.py
This resolves Issue #116. I attempt to use a more sophisticated regular expression relying on the assumption that the file have a common prefix, a number, then a common suffix. This solution works for the existing AHF test data as well as the data supplied in Issue #116.
> Use smarter regexes to get AHF naming scheme.

- doc/source/Analysis.rst
- tests/test_pipelines.py
- ytree/analysis/analysis_operators.py
- ytree/analysis/analysis_pipeline.py
Instead of trying to specifically detect boolean return values from analysis pipeline operations, we now interpret any non-None return value as a boolean for filtering. This avoids increasingly complex checks to correctly detecting all boolean-like values. This also adds an `always_do` option to `add_operation`, which allows an operation to be run regardless of prior filters. This can be useful for adding cleanup functions at the ends of pipelines.
> Fix analysis pipeline operation filtering and add always_do option.

- ytree/frontends/consistent_trees/arbor.py
Sometimes the locations.dat file has extra columns than the sample data. This fixes an inconsistency in getting the filenames from that file.
> Get filename from correct part of line in consistent-trees format.

- ytree/frontends/ahf/arbor.py
- ytree/frontends/ahf/io.py
This resolves Issue #147. I've made it slightly easier to adjust the precision of the redshift in the file naming convention and check if the redshift is less than the minimum value given by this precision.
This also resolved Issue #148. I was not calculating the file index using the function argument.
> Fix two AHF frontend issues.

- .circleci/config.yml
- fix-junit.py
This adds a simple script to modify the contents of the xml file produced by pytest on circleci so that the file entry reflects the test script and not the file of the base class. I hope this will allow the circleci parallelism to work a bit better.
> Add script to fix filename in junit output.

- .circleci/config.yml
- doc/source/Loading.rst
- tests/frontends/test_ahf.py
- ytree/data_structures/arbor.py
- ytree/frontends/ahf/__init__.py
- ytree/frontends/ahf/arbor.py
- ytree/frontends/ahf/fields.py
- ytree/frontends/ahf/io.py
- ytree/frontends/ahf/misc.py
- ytree/utilities/misc.py
This adds support for a new AHF format where the entire tree structure is stored in a single ascii file rather than one mtree file per catalog. This is a duplicate to PR #151, but I couldn't get the ci testing to update there.
> Update AHF format

- setup.py
- tests/test_yt_selection.py
- ytree/data_structures/io.py
- ytree/data_structures/save_arbor.py
- ytree/frontends/gadget4/io.py
This replaces the deprecated `unyt.uconcatenate` with `np.concatenate`, as per the direction of unyt 3.0.
> Replace deprecated unyt.uconcatenate function

- .circleci/config.yml
- setup.py
This declares support for python 3.12 and eliminates testing with python 3.9 and yt-dev since yt no longer supports 3.9.
> Update version support

- .circleci/config.yml
- .readthedocs.yaml
- tests/conftest.py
- tests/test_yt_selection.py
- ytree/utilities/testing.py
Tests have been failing because the default resource class changed to only allow 2 processors instead of 4. We explicitly ask for the large class and remove the daily tests to cut down on resources.
Update: for whatever reason, circle just won't run the parallel tests anymore, always claiming it can't spawn processes even when they should be available. Whatever, I give up for now. I'll try to remember to test them locally from time to time.
> Add resource_class for testing and remove daily tests.

- .circleci/config.yml
- doc/source/Loading.rst
- tests/frontends/test_ahf.py
- ytree/data_structures/arbor.py
- ytree/frontends/ahf/__init__.py
- ytree/frontends/ahf/arbor.py
- ytree/frontends/ahf/fields.py
- ytree/frontends/ahf/io.py
This addresses Issue #157. The key to the data shared in that PR is that it is using a different prefix and suffixes for some of the files, but they are generally still of the expected format. The easiest way I could think to deal with this is to allow the user to specify some of the naming conventions themselves in a dictionary at load. For example:
```
a = ytree.load(
"AHF.B25_N256_CDM_1LPT.snap_055.parameter",
name_config={"ahf_prefix": "AHF.B25_N256_CDM_1LPT",
"mtree_prefix": "MTREE.B25_N256_CDM_1LPT.z39_adapt",
"mtree_suffix": ".AHF_croco"})
```
> Add ability to customize file naming conventions for AHF.

- doc/source/Arbor.rst
- doc/source/Parallelism.rst
- doc/source/api_reference.rst
- ytree/data_structures/arbor.py
- ytree/data_structures/fields.py
- ytree/utilities/exceptions.py
This closes issue #130. I've added documentation for the cosmology calculator as well as the arr and quan helper attributes for creating unyt arrays and quantities. I've also converted the cosmology attribute into a cached property, which has the added benefit of getting rid of the warning messages if cosmological parameters aren't available. I've also made some intersphinx references explicit to avoid confusion.
> Add documentation for helpful attributes and make cosmology calculator a cached_property

- ytree/data_structures/tree_node.py
Another small gem from the p2p branch. This is a minor speedup for `get_node`. When I implemented it originally, I forgot that we shouldn't do this if using forest selection since that uses an absolute index. I fixed it by only doing this for forest and progenitor selection.
> Minor speedup for get_node

- README.md
- doc/source/Installation.rst
- doc/source/conf.py
- scripts/get_version.py
- ytree/__init__.py
This implements a function to scrape `ytree/__init__.py` to get the current version so we only have one place to update. I also changed the README to point to the docs for citation information for the same reason.
> Refactor to versioning and citation information

- .circleci/config.yml
- README.md
- pyproject.toml
This updates the circleci python versions used for testing, including adding a python 3.13. If it works, we will include that as a supported version and add a badge for it.
> Update python versions
